name: video_4k_converter
description: Real 4K Converter Pro
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  permission_handler: ^11.0.0
  ffmpeg_kit_flutter_new: ^1.0.0
  path_provider: ^2.1.1

flutter:
  uses-material-design: true
